### ISSUE TITLE
Unknown asset format 14

### ISSUE THREAD

**Issue by chyuliy** [ata4/disunity#108]
Create simple scene with Unity3D 5. Import ThirdPersonalCh., ocean, water.
Build game for Android. Extract from APK bin\Data folder.
Now see files: sharedassets0.assets.split0...sharedassets0.assets.split47
Try extract by command: disunity extract sharedassets*.assets.split*
Get error for all:

[info] sharedassets0.assets.splitX
[warning] FileCommand: Can't process sharedassets0.assets.splitX, caused by info.ata4.unity.asset.AssetException: Unknown asset format 14
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
        at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.java:97)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

**Comment by ata4** [comment]
Yeah, Unity 5 support is on the to-do list, just like many other things right now.
