### ISSUE TITLE
Memory error with Disunity I wasn't having before

### ISSUE THREAD

**Issue by Spike315** [ata4/disunity#113]
I've used a Disunity for quite a while but now I constantly get this error when I use it;

[error] DisUnityCli: Fatal error, caused by java.lang.OutOfMemoryError: Java heap space
        at info.ata4.unity.serdes.Deserializer.readArray(Deserializer.java:222)
        at info.ata4.unity.serdes.Deserializer.readCollection(Deserializer.java:
250)
        at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:126)
        at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:95)
        at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:134)
        at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:95)
        at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:134)
        at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:95)
        at info.ata4.unity.serdes.Deserializer.deserialize(Deserializer.java:72)

        at info.ata4.unity.cli.extract.AssetExtractor.extract(AssetExtractor.jav
a:160)
        at info.ata4.unity.cli.cmd.ExtractCmd.processAsset(ExtractCmd.java:43)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.ja
va:100)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90
)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

I spent an hour trying to fix the problem but none of the fixes I found on google search worked.

Any ideas on what to do?

**Comment by ankilla** [comment]
Try this
Install Java 64bit based on your OS
Update to latest version (Ver 8.40) this could solve your problem or else increase the jvm default memory limit
http://www.wikihow.com/Increase-Java-Memory-in-Windows-7

**Comment by Spike315** [comment]
Thanks, but those are fixes I already tried to no avail. It just started happening out of the blue and I just can't find a reason as to why it's happening.

I haven't made any changes to my hardware, running the same setup I've always had which Disunity didn't have any problems with before.

**Comment by ankilla** [comment]
Can you give me the link to the unity file so I will check whether its working for me or not

**Comment by Spike315** [comment]
http://www.mediafire.com/download/g9h7tc9upfsmcv3/resources.assets

**Comment by ankilla** [comment]
What command you had used
I tried with "extract" i didnt got memory error but got some other error,
attached image,

​
Again I used extract-raw it extracted files but donno how much its useful
to you.

**Comment by Spike315** [comment]
disunity extract "resources.assets"
