### ISSUE TITLE
but how to pack the file again？

### ISSUE THREAD

**Issue by jy03344894** [ata4/disunity#12]
this unpack works great，
but how to pack the file again？

**Comment by wbulot** [comment]
I have the same problem as Migano.
Any solutions ?

**Comment by SnakeTheRipper** [comment]
After using bundle-extract, I get a CAB-nameofthefile.000 .

How can I edit the assets inside that file ? Or inject files into that file ? Anyone has achieved it ?

Thanks !

**Comment by 60f39878ec348ae** [comment]
how i import mesh obj to Unity Asset Explorer it's used for unity raw data? when i export 
what is unity raw data? and how to convert to that?

thanks very much

**Comment by lcplpunishment** [comment]
I would also like to see the option to repack / add content to assetfiles. I would like to use the option for modding games. Imho cheaters are not really a big concern, those who want to cheat already are already able to do it, and most of them are using "driver hacking" or scripts which can be found by a google search.
I know other ways to modify the asset files, but if disunity was able to add files it would be a complete package. Thanks for your great work so far :)

**Comment by Necklaces** [comment]
I'm just gonna jump in like everybody else.
Love the work you have done! 
I too am interested in repackaging into .assets files, and if there's anything I can do, I would gladly help!

**Comment by ExcelledProducts** [comment]
Is there a way to recompile the extracted files back into a .unity3d file???

**Comment by Necklaces** [comment]
@ExcelledProducts As long as they are .unity3d files you can run bundle-inject to "recompile the extracted files back". Try reading the README.md next time.

**Comment by ExcelledProducts** [comment]
@Necklaces I assume that won't work for repacking the .asset files correct?

**Comment by Necklaces** [comment]
@ExcelledProducts That's what this issue/thread is about, so yeah, that's correct as of now I suppose. .asset repackaging/injection is not possible with disunity (yet?).

**Comment by matheuslessarodrigues** [comment]
When I try to run bundle-inject in my project, I get this stack trace:

```
[error] DisUnityCli: Fatal error, caused by java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Unknown Source)
        at java.nio.DirectByteBuffer.<init>(Unknown Source)
        at java.nio.ByteBuffer.allocateDirect(Unknown Source)
        at info.ata4.util.io.lzma.LzmaBufferUtils.encode(LzmaBufferUtils.java:84)
        at info.ata4.util.io.lzma.LzmaBufferUtils.encode(LzmaBufferUtils.java:117)
        at info.ata4.unity.asset.bundle.AssetBundle.save(AssetBundle.java:173)
        at info.ata4.unity.cli.cmd.BundleInjectCmd.processAssetBundle(BundleInjectCmd.java:70)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetBundleFile(AssetCommand.java:111)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:86)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)
```

We're trying to obfuscate our game's .dll after the WebPlayer build
We appreciate your help! Thanks!

**Comment by Necklaces** [comment]
@matheuslessarodrigues 
Hi there,
this is an issue on re-packaging asset files, your problem seems unrelated, so I highly recommend making your own issue.

As for your current error, you've run out of buffer memory, I suggest increasing your JVM's buffer memory limit, in your JVM you could add this option:

    XX:MaxDirectMemorySize=512m

We'll start with that at least, pretty sure it's not a memory leak.

**Comment by matheuslessarodrigues** [comment]
Oh ok! Sorry for the post in the wrong place.
Anyway, thanks for the tip! I'll try it.
