### ISSUE TITLE
Unity 4.6.3

### ISSUE THREAD

**Issue by JackWuHu** [ata4/disunity#122]
hi ata4,

disunity can not extract unity 4.6.3 asset file. I got two problems:

1. the version warning.
 [warning] FieldTypeMap: Unprecise match for ClassID 1 (required: 4.6.3f1, availa
ble: 4.1.0f4)
[warning] FieldTypeMap: Unprecise match for ClassID 4 (required: 4.6.3f1, availa
ble: 4.1.0f4)

2. 
[error] DisUnityCli: Fatal error, caused by java.lang.OutOfMemoryError: Java hea
p space
        at java.util.ArrayList.<init>(Unknown Source)
        at info.ata4.unity.serdes.Deserializer.readArray(Deserializer.java:238)
        at info.ata4.unity.serdes.Deserializer.readCollection(Deserializer.java:
250)
        at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:126)
        at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:95)
        at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:134)
        at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:95)
        at info.ata4.unity.serdes.Deserializer.deserialize(Deserializer.java:72)

        at info.ata4.unity.cli.extract.AssetExtractor.extract(AssetExtractor.jav
a:160)
        at info.ata4.unity.cli.cmd.ExtractCmd.processAsset(ExtractCmd.java:43)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.ja
va:100)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90
)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

could you help for this?

**Comment by eisnerguy1** [comment]
Getting the same issue while trying to extract files from Sonic Runners.
