### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by gapipro** [ata4/disunity#124]

**Comment by ata4** [comment]
That one has been fixed by [this pull](https://github.com/ata4/disunity/pull/127) I think.

**Comment by GabLeRoux** [comment]
I had the error, it's about using the right java version. This error will happen if you try to run the jar file with java 1.7

```
$ java -jar disunity/disunity.jar
```

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: info/ata4/disunity/cli/DisUnityCli : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

You can verify your installed java version with

```
java -version
```

Solution is to [install java 1.8, here's a guide](https://forum.shakacode.com/t/install-java-1-8-on-mac-os-el-capitan/389).
