### ISSUE TITLE
Unity 5 extracting

### ISSUE THREAD

**Issue by saggycondom** [ata4/disunity#135]
I was trying to extract a .unity3d package and ended up with this error:
[info] Wetshaders.unity3d\sharedassets0.assets
[warning] FileCommand: Can't process Wetshaders.unity3d, caused by info.ata4.uni
ty.asset.AssetException: Unknown asset format 15
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetBundleFile(AssetComm
and.java:141)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:86
)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

As you may have read, I am trying to extract a shader file, and looking at your recent replies, I have seen that this is a issue resolved in 0.4. At it current state according to you shaders can be extracted perfectly fine? If that is so, please release a pre-release version so we can atleast get started on extracting :(

**Comment by heikomilke** [comment]
bump
