### ISSUE TITLE
[warning] FileCommand: Can't process .unity3d, caused by info.ata4.unity.asset.AssetException: Unknown asset format 15

### ISSUE THREAD

**Issue by srikant** [ata4/disunity#149]
Unable to perform extract command, please help...

java -jar disunity.jar extract game.unity3d
[info] DisUnity v0.3.4
[info] game.unity3d
[info] Uncompressing asset bundle, this may take a while
[info] game.unity3d/sharedassets0.assets
[warning] FileCommand: Can't process game.unity3d, caused by info.ata4.unity.asset.AssetException: Unknown asset format 15
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
	at info.ata4.unity.cli.cmd.AssetCommand.processAssetBundleFile(AssetCommand.java:141)
	at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:86)
	at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
	at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
	at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
	at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

**Comment by dongvanhung** [comment]
This is game  made with Unity 5 version. You must wait the author build the latest version that support extract resources from Unity 5.

**Comment by Lolekowy** [comment]
I also have the same problem, game was made with Unity 5 engine.

Last update was almost a year ago. I hope that ata is able to make it extract from unity 5 :(

**Comment by Neogene** [comment]
Hi how could we update the sources to add unity 5 support?

**Comment by Kallin** [comment]
:+1:

**Comment by Kallin** [comment]
Btw it looks like @ivanpopelyshev is hard at work on this judging from recent commits. I may try building from source and see how far I can get. There is a very popular card game that recently moved to unity 5 which I'm interested in seeing the textures for!

**Comment by ivanpopelyshev** [comment]
Well, it works on certain minecraft clone :)

@Kallin do you know how to convert tex do dds, by the way?

**Comment by Kallin** [comment]
@ivanpopelyshev I've never tried, is it a problem?

**Comment by Keril** [comment]
Please update it to work with Unity 5. Disunity is a great tool that I used often and I am not able to because files are from game made in Unity 5.

Thanks for all the great work so far!
