### ISSUE TITLE
extract fail

### ISSUE THREAD

**Issue by easeyang** [ata4/disunity#154]
env:
os:osx 10.11.1
java:1.8.0_60

error info:
java -jar disunity.jar extract resources.assets 

[info] DisUnity v0.3.4
[info] resources.assets
[warning] FileCommand: Can't process resources.assets, caused by info.ata4.unity.asset.AssetException: Unknown asset format 15
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
	at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
	at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.java:97)
	at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90)
	at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
	at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
	at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
	at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

**Comment by Seegras** [comment]
issue #163
