### ISSUE TITLE
Unknown asset format 15

### ISSUE THREAD

**Issue by larryhou** [ata4/disunity#163]
$ disunity extract resources.assets 
[info] DisUnity v0.3.4
[info] resources.assets
[warning] FileCommand: Can't process resources.assets, caused by info.ata4.unity.asset.AssetException: Unknown asset format 15
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
	at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
	at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.java:97)
	at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90)
	at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
	at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
	at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
	at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

I've uploaded related file to my github, you can download through the following link:
https://github.com/larryhou/cdn/blob/master/resources.assets?raw=true

**Comment by larryhou** [comment]
disunity is an awesome tool, I love it very much, so if you can fix this problem, I'm really appreciated from the bottom of my heart

**Comment by lanrat** [comment]
I'm having the same issue too...
