### ISSUE TITLE
extract failed & Unity5.3.0f4

### ISSUE THREAD

**Issue by MaNGOS-FAN** [ata4/disunity#164]
[warning] FileCommand: Can't process sharedassets0.assets, caused by info.ata4.unity.asset.AssetException: Unknown ass
et format 15
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:145)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
        at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.ja
va:97)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90
)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

**Comment by Seegras** [comment]
this is issue #163
