### ISSUE TITLE
Fail to use bundle unpack 

### ISSUE THREAD

**Issue by shane007no** [ata4/disunity#166]
I use bundle unpack to extract a resources.assets file  ,but got failed with the follow error message, how can i do?

D:\disunity>disunity.bat bundle unpack d:\disunity\unity\*.* 
[warning] BundleUnpack: Can't unpack asset bundle d:\disunity\unity\resources.assets, caused by java.io.EOFException
        at info.ata4.io.buffer.source.ReadableByteChannelSource.requestRead(ReadableByteChannelSource.java:114)
        at info.ata4.io.buffer.source.SeekableByteChannelSource.requestRead(SeekableByteChannelSource.java:150)
        at info.ata4.io.DataReader.readInt(DataReader.java:83)
        at info.ata4.io.DataReader.readUnsignedInt(DataReader.java:118)
        at info.ata4.junity.bundle.BundleHeader.read(BundleHeader.java:86)
        at info.ata4.io.DataReader.readStruct(DataReader.java:37)
        at info.ata4.junity.bundle.BundleReader.read(BundleReader.java:46)
        at info.ata4.disunity.cli.command.bundle.BundleUnpack.runFile(BundleUnpack.java:64)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

**Comment by tigerhu67** [comment]
i have same issue too.

**Comment by ssokolow** [comment]
I get the same failure with resources.assets from Desktop Dungeons, which Unity Assets Explorer 1.2 understands.

**Comment by ata4** [comment]
".assets" files aren't bundles, so any of "bundle" commands won't work on them. Bundle files usually have the ".unity3d" extension.

**Comment by ssokolow** [comment]
Ahh. Probably a good idea to write a FAQ detailing what should work, what shouldn't work, and which commands to use for which tasks.

I have programming experience and I was still guessing my way around disunity for lack of documentation which clearly maps low-level commands to high-level tasks.

**Comment by tigerhu67** [comment]
@ata4  but the old version(v.0.3.4) can work for ".assets".

**Comment by Drullkus** [comment]
Can confirm, I can extract .asset files with other window-based extractors, but those extractors are not runnable on my macbook :(
