### ISSUE TITLE
DisUnityCli: Fatal error - while Unpacking

### ISSUE THREAD

**Issue by ankilla** [ata4/disunity#167]
While unpacking unity file I got the following error

java -jar "%~dp0\disunity.jar" bundle unpack unity.unity3d

[error] DisUnityCli: Fatal error, caused by java.lang.IllegalArgumentException:
Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Unknown Source)
        at info.ata4.disunity.cli.command.bundle.BundleCommand.runFileRecursive(BundleCommand.java:35)
        at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)

        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46) 
Caused by: java.io.IOException: Stream is too short
        at info.ata4.io.lzma.LzmaDecoderProps.fromInputStream(LzmaDecoderProps.java:31)
        at net.contrapunctus.lzma.DecoderThread.run(DecoderThread.java:53)

**Comment by ankilla** [comment]
@ata4 any info about the above error

**Comment by TempoTurtle** [comment]
I have the same problem! Please help!
