### ISSUE TITLE
Self-suppression not permitted

### ISSUE THREAD

**Issue by XN1TE** [ata4/disunity#173]
While trying to unpack I encountered the following error:

---------------------------------------------------------------------------------------------------------
[error] DisUnityCli: Fatal error, caused by java.lang.IllegalArgumentException:
Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Unknown Source)
        at info.ata4.disunity.cli.command.bundle.BundleUnpack.runFile(BundleUnpa
ck.java:105)
        at info.ata4.disunity.cli.command.FileCommand$$Lambda$2/30125492.accept(
Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)

        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)
Caused by: java.io.IOException: Stream is too short
        at info.ata4.io.lzma.LzmaDecoderProps.fromInputStream(LzmaDecoderProps.j
ava:31)
        at net.contrapunctus.lzma.DecoderThread.run(DecoderThread.java:53)
---------------------------------------------------------------------------------------------------------

Any ideas what might be causing this or what the fix is?

**Comment by MakuraYami** [comment]
It's a newer version that disunity does not support yet, I'm having this issue too with bundles or assets of version 5.3.2f1

**Comment by Puggyblue999** [comment]
I'm having a similar error, however I'm trying to unpack a bundle of Unity 2.x.x. I tried using v0.4 and v0.5 but neither worked.

**Comment by liszto** [comment]
I tried to patch all of this... But too painful and now I'm in the same behaviour than you have.

I had the possibility to manage UnityFS format but now i'm stuck with this LZMA issue...

Anyone has solved this ?

**Comment by liszto** [comment]
I'm progressing....
But I never used LZMA libraries and didn't use such low level libraries and java (so it's quite painful) to do stuff like this.
Now I have invalid LZMA properties. Even when I compile the code base of LZMA libraries (quite weird)
