### ISSUE TITLE
No such file?

### ISSUE THREAD

**Issue by Octolus** [ata4/disunity#196]
disunity asset unpack item.obj

[warning] AssetUnpack: Can't unpack asset file item.obj\CAB-item, caused by java.nio.file.NoSuchFileException: item.obj\CAB-item
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at info.ata4.disunity.cli.command.asset.AssetUnpack.runSerializedFile(AssetUnpack.java:56)
        at info.ata4.disunity.cli.command.asset.AssetCommand.lambda$runFileRecursive$1(AssetCommand.java:49)
        at info.ata4.util.function.IOConsumer.lambda$uncheck$10(IOConsumer.java:30)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.asset.AssetCommand.runFileRecursive(AssetCommand.java:45)
        at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

[warning] AssetCommand: Can't open asset file test, caused by java.nio.file.AccessDeniedException: test
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at info.ata4.io.DataReaders.forFile(DataReaders.java:53)
        at info.ata4.junity.serialize.SerializedFileReader.<init>(SerializedFileReader.java:79)
        at info.ata4.disunity.cli.command.asset.AssetCommand.runFileRecursive(AssetCommand.java:58)
        at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

**Comment by Cyberman-tM** [comment]
This might be a problem with the path. I have the same error, when I moved the files to a root directory, I got a different error (EOFException).
The latter might just be because the file isn't usable, though.

Looking at your second error, though, maybe the user running the program doesn't have the rights?

**Comment by Mactastic1-5** [comment]
There's nothing to unpack or extract, item.obj is a 3D model. Please close!
