### ISSUE TITLE
Bundle Pack issues...

### ISSUE THREAD

**Issue by niznet** [ata4/disunity#202]
what the correct command for a .unity3d that has been extracted?
i always failed....

what i use:

disunity bundle pack NavalFrontLine

[error] DisUnityCli: Fatal error, caused by java.lang.NullPointerException
        at info.ata4.disunity.cli.command.bundle.BundlePack.runFile(BundlePack.j
ava:47)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)

```
    at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)
```

**Comment by RupW** [comment]
The current version doesn't like relative filenames in the current directory. Try `.\NavalFrontLine` or replace it with the full path to `NavalFrontLine`.

(To repack you will also need a .json bundle properties file that you can get from unpacking the original bundle with `-p`, and probably worth glancing at the contents to see if there's anything that needs updating for your changes.)

**Comment by Mactastic1-5** [comment]
As said above, you need a property file to pack files into a Unity asset bundle file. Please close!
