### ISSUE TITLE
Extract Issues

### ISSUE THREAD

**Issue by sibu12345** [ata4/disunity#206]
Currently using Disunity 0.3.4 no experience in programming.
I'm trying to Rip game files which I followed instructions from this site:
http://soccerspiritsforum.com/threads/soccer-spirits-full-rip.1978/

Apparently I'd have to bundle extract then extract. My bundle extracting phase seems to run but looks odd compared to others:

C:\Disunity>disunity bundle-extract files*/
[info] DisUnity v0.3.4
[info] files
[info] files\100001_cs
[info] files\10101_co
[info] files\10101_cs
[info] files\10102_co
[info] files\10102_cs
[info] files\10103_co
[info] files\10103_cs
[info] files\10104_co
[info] files\10104_cs
[info] files\10105_co
[info] files\10105_cs\

(To show the few of them)

and when I try to extract:

C:\Disunity>disunity extract files*/
[info] DisUnity v0.3.4
[info] files
[info] files\100001_cs
[error] DisUnityCli: Fatal error, caused by java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Unknown Source)
        at info.ata4.io.buffer.ByteBufferUtils.getSlice(ByteBufferUtils.java:210)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:127)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
        at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.java:97)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.processDirectory(FileCommand.java:44)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:54)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

When I try doing it on 0.5.0 
I'd get this on every file:
C:\Users\Arno\Desktop\disunity>disunity bundle unpack files/*

[warning] BundleUnpack: Can't unpack asset bundle files\snd_30104_battle1, caused by info.ata4.junity.bundle.BundleException: Invalid signature
        at info.ata4.junity.bundle.BundleReader.read(BundleReader.java:50)
        at info.ata4.disunity.cli.command.bundle.BundleUnpack.runFile(BundleUnpack.java:64)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

Any Idea why?
Java version 8 Update 101 (build 1.8.0_101-b13)

**Comment by zklm** [comment]
I'm assuming you're trying this on SS assets post-1.27 patch (29 Sep 2016), if so, Unity version for SS was updated and it's now using UnityFS assets, not UnityWeb.

**Comment by ata4** [comment]
Yeah, Disunity currently doesn't properly support UnityFS, but I'm working on a Python port that will support UnityFS, UnityRaw and UnityWeb.

**Comment by jorgerobles** [comment]
There's already some Python Code that you could check. Maybe you could help
each other: https://github.com/HearthSim/UnityPack

**Comment by ata4** [comment]
I've actually checked UnityPack already and used some parts to improve my code a bit. I prefer my approaches for the most parts, though.

**Comment by Mactastic1-5** [comment]
Please close this issue!
