### ISSUE TITLE
Unity 4.7.2

### ISSUE THREAD

**Issue by hendryten** [ata4/disunity#210]
Got this issue with 4.7.2.
Is it currently supported?

```
[warning] AssetCommand: Can't open asset bundle asset.assets, caused by java.io.EOFException
    at info.ata4.io.buffer.source.ReadableByteChannelSource.requestRead(ReadableByteChannelSource.java:114)
    at info.ata4.io.DataReader.readInt(DataReader.java:83)
    at info.ata4.junity.bundle.BundleReader.read(BundleReader.java:63)
    at info.ata4.disunity.cli.command.asset.AssetCommand.runFileRecursive(AssetCommand.java:41)
    at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
    at java.util.ArrayList.forEach(Unknown Source)
    at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
    at info.ata4.disunity.cli.command.Command.run(Command.java:50)
    at info.ata4.disunity.cli.command.Command.run(Command.java:50)
    at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
    at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)
```

**Comment by Mactastic1-5** [comment]
You typed the command improperly. The file, asset.assets is an asset, so you would use an asset command and not an asset bundle command. Asset bundle is .unity3d and an asset is .resources, .assets, .assets, etc. You won't be able to get any of the serialized objects in the assets file. Please close.
