### ISSUE TITLE
unable to unpack 

### ISSUE THREAD

**Issue by iluvatar80** [ata4/disunity#216]
`I:\disunity_v0.5.0>disunity.bat bundle unpack sounds0.unity3d -o i:/unpack
[warning] BundleUnpack: Can't unpack asset bundle sounds0.unity3d, caused by info.ata4.junity.bundle.BundleException: Invalid signature
        at info.ata4.junity.bundle.BundleReader.read(BundleReader.java:50)
        at info.ata4.disunity.cli.command.bundle.BundleUnpack.runFile(BundleUnpack.java:64)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)`

**Comment by Mactastic1-5** [comment]
You didn't provide additional information. I think Error messages should be implemented that give you an actual error message. Please close this issue.
