### ISSUE TITLE
how to unpack 

### ISSUE THREAD

**Issue by timlin78988** [ata4/disunity#222]
I've have problem in 0.3.4 ,please help
C:\Users\Henry\Downloads\disunity1>disunity extract 1.unity3d
[info] DisUnity v0.3.4
[info] 1.unity3d
[error] DisUnityCli: Fatal error, caused by java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Unknown Source)
        at info.ata4.io.buffer.ByteBufferUtils.getSlice(ByteBufferUtils.java:210
)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:127)
        at info.ata4.unity.asset.AssetFile.load(AssetFile.java:105)
        at info.ata4.unity.asset.AssetFile.open(AssetFile.java:58)
        at info.ata4.unity.cli.cmd.AssetCommand.processAssetFile(AssetCommand.ja
va:97)
        at info.ata4.unity.cli.cmd.AssetCommand.processFile(AssetCommand.java:90
)
        at info.ata4.unity.cli.cmd.FileCommand.processPath(FileCommand.java:58)
        at info.ata4.unity.cli.cmd.FileCommand.run(FileCommand.java:76)
        at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:110)
        at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:123)

**Comment by Rocksnotch** [comment]
I have a java issue as well.
