### ISSUE TITLE
Have an issue trying to extract a resources.assets file

### ISSUE THREAD

**Issue by Rocksnotch** [ata4/disunity#223]
I keep getting this:

C:\Users\William\Desktop\disunity_v0.5.0>disunity asset unpack resources.assets
[warning] AssetCommand: Can't open asset file resources.assets, caused by java.io.EOFException
        at info.ata4.io.buffer.source.ReadableByteChannelSource.requestRead(ReadableByteChannelSource.java:114)
        at info.ata4.io.buffer.source.SeekableByteChannelSource.requestRead(SeekableByteChannelSource.java:150)
        at info.ata4.io.DataReader.readInt(DataReader.java:83)
        at info.ata4.junity.serialize.objectinfo.ObjectInfoV2.read(ObjectInfoV2.java:36)
        at info.ata4.junity.serialize.objectinfo.ObjectInfoV3.read(ObjectInfoV3.java:34)
        at info.ata4.io.DataReader.readStruct(DataReader.java:37)
        at info.ata4.junity.serialize.objectinfo.ObjectInfoTableV2.read(ObjectInfoTableV2.java:34)
        at info.ata4.io.DataReader.readStruct(DataReader.java:37)
        at info.ata4.junity.serialize.SerializedFileMetadata.read(SerializedFileMetadata.java:154)
        at info.ata4.io.DataReader.readStruct(DataReader.java:37)
        at info.ata4.junity.serialize.SerializedFileReader.readMetadata(SerializedFileReader.java:130)
        at info.ata4.junity.serialize.SerializedFileReader.read(SerializedFileReader.java:107)
        at info.ata4.disunity.cli.command.asset.AssetCommand.runFileRecursive(AssetCommand.java:59)
        at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
        at java.util.ArrayList.forEach(Unknown Source)
        at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.Command.run(Command.java:50)
        at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
        at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

Do I have to reinstall java or tell it java is somewhere else, or am I doing something 100% wrong?

**Comment by Rocksnotch** [comment]
ANY help would be great!
