### ISSUE TITLE
I can`t unpack the resource with disunity_v0.5.0...why?

### ISSUE THREAD

**Issue by CavanLife** [ata4/disunity#224]
java -jar /Users/mono/Desktop/disunity_v0.5.0/disunity.jar asset unpack  /Users/mono/Desktop/Data/*.assets 

-----------------------
[warning] AssetCommand: Can't open asset file /Users/mono/Desktop/Data/sharedassets4.assets, caused by java.io.EOFException
	at info.ata4.io.buffer.source.ReadableByteChannelSource.requestRead(ReadableByteChannelSource.java:114)
	at info.ata4.io.buffer.source.SeekableByteChannelSource.requestRead(SeekableByteChannelSource.java:150)
	at info.ata4.io.DataReader.readInt(DataReader.java:83)
	at info.ata4.io.DataReader.readUnsignedInt(DataReader.java:118)
	at info.ata4.junity.serialize.objectinfo.ObjectInfoV2.read(ObjectInfoV2.java:34)
	at info.ata4.junity.serialize.objectinfo.ObjectInfoV3.read(ObjectInfoV3.java:34)
	at info.ata4.io.DataReader.readStruct(DataReader.java:37)
	at info.ata4.junity.serialize.objectinfo.ObjectInfoTableV2.read(ObjectInfoTableV2.java:34)
	at info.ata4.io.DataReader.readStruct(DataReader.java:37)
	at info.ata4.junity.serialize.SerializedFileMetadata.read(SerializedFileMetadata.java:154)
	at info.ata4.io.DataReader.readStruct(DataReader.java:37)
	at info.ata4.junity.serialize.SerializedFileReader.readMetadata(SerializedFileReader.java:130)
	at info.ata4.junity.serialize.SerializedFileReader.read(SerializedFileReader.java:107)
	at info.ata4.disunity.cli.command.asset.AssetCommand.runFileRecursive(AssetCommand.java:59)
	at info.ata4.disunity.cli.command.RecursiveFileCommand.runFile(RecursiveFileCommand.java:52)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at info.ata4.disunity.cli.command.FileCommand.run(FileCommand.java:32)
	at info.ata4.disunity.cli.command.Command.run(Command.java:50)
	at info.ata4.disunity.cli.command.Command.run(Command.java:50)
	at info.ata4.disunity.cli.command.DisUnityRoot.run(DisUnityRoot.java:62)
	at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:46)

**Comment by maritaria** [comment]
Probably because the asset file is of a newer version that the current tool cannot read

**Comment by RuohengLiu** [comment]
i got the same problem when i try to use this tool to unpack the gwent.

**Comment by maritaria** [comment]
If you want to extract things from Unity 5 you can use [this tool](https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor)
