### ISSUE TITLE
OutOfMemoryError issue while deserialize

### ISSUE THREAD

**Issue by nkarabulut** [ata4/disunity#40]
[error] DisUnityCli: Fatal error, caused by java.lang.OutOfMemoryError: Java heap space
    at java.util.ArrayList.<init>(ArrayList.java:148)
    at info.ata4.unity.serdes.Deserializer.readArray(Deserializer.java:230)
    at info.ata4.unity.serdes.Deserializer.readCollection(Deserializer.java:242)
    at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:135)
    at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:104)
    at info.ata4.unity.serdes.Deserializer.readValue(Deserializer.java:143)
    at info.ata4.unity.serdes.Deserializer.readObject(Deserializer.java:104)
    at info.ata4.unity.serdes.Deserializer.deserialize(Deserializer.java:74)
    at info.ata4.unity.cli.extract.AssetExtractor.extract(AssetExtractor.java:159)
    at info.ata4.unity.cli.action.ExtractAction.processAsset(ExtractAction.java:53)
    at info.ata4.unity.cli.DisUnityProcessor.processAsset(DisUnityProcessor.java:242)
    at info.ata4.unity.cli.DisUnityProcessor.run(DisUnityProcessor.java:119)
    at info.ata4.unity.cli.DisUnityCli.run(DisUnityCli.java:119)
    at info.ata4.unity.cli.DisUnityCli.main(DisUnityCli.java:55)

**Comment by ZioYuri78** [comment]
"I updated the database file for Unity 4.5. You can update your local installation by placing this file in the DisUnity folder where disunity.jar is located, then it should be able to read newer standalone assets."

Hi ata4, looks like the file you llinked is no longer available, can you upload it again?

**Comment by ata4** [comment]
The file is now located [here](https://github.com/ata4/disunity/raw/master/src/resources/types.dat). 0.3.4 should support Unity 4.5 out of the box, though.

**Comment by ZioYuri78** [comment]
Thank you very much :+1:

**Comment by baongoccarrot** [comment]
So how about Unity 4.6 database file
